In [10]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from time import sleep
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import csv

In [2]:
path = "C:\Program Files\Google\Chrome\Applicationchromedriver.exe"
service = Service(executable_path=path)
driver = webdriver.Chrome(service=service)
driver.get('https://www.gharghaderi.com/house-for-sale/')
driver.maximize_window()

In [19]:
#press more listing button till end
for i in range(1,300):
    time.sleep(5)
    more_button = driver.find_element(by="xpath",value='/html/body/div/div/div/div/span/button')
    more_button.click()

In [9]:
house_details_link = driver.find_elements(by="xpath",value='/html/body/div/div/div/div/a')

In [17]:
#get house links
list_of_house_links=[]
for house in house_details_link:
    house_link=house.get_property("href")
    list_of_house_links.append(house_link)
    print(house_link)

In [15]:
#put house links in csv file

with open('house_links_ghar.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    for link in list_of_house_links:
        writer.writerow([link])

In [18]:
## data sorting

In [73]:
with open('house_links_ghar.csv') as csv_file:
    csv_reader = csv.reader(csv_file)
    urls = [row[0] for row in csv_reader]

In [80]:
data_list=[]
start_time = time.time()

for url in urls:
    try:
        driver.get(url)
        data_dict = {}
        title = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.first-section > h1')
        location = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.first-section > div.h2 > table > tbody > tr > td.upper')

        landd = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.first-section > div.h2 > table > tbody > tr > td:nth-child(3)')
        a = landd.text
        land = a.strip("\n Land")

        roaddis = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.first-section > div.h2 > table > tbody > tr > td:nth-child(4)')
        aa = roaddis.text
        road = aa.strip("\n Road")

        pricemon = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.first-section > div.h2 > table > tbody > tr > td:nth-child(2)')
        aa = pricemon.text
        price = aa.strip("\n रु. Price")

        bedroom = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.last-section > div:nth-child(15) > table > tbody > tr:nth-child(2) > td.test1')
        bathroom = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.last-section > div:nth-child(15) > table > tbody > tr:nth-child(3) > td.test1')
        builty = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.last-section > div:nth-child(14) > table > tbody > tr:nth-child(6) > td.test1')
        parking = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.last-section > div:nth-child(15) > table > tbody > tr:nth-child(6) > td.test1')
        direction = driver.find_element(By.CSS_SELECTOR, value='body > div.wrapper > div > div.subcontent > div.last-section > div:nth-child(15) > table > tbody > tr:nth-child(1) > td.test1')


        data_dict['title'] = title.text
        data_dict['price'] = price
        data_dict['location'] = location.text
        data_dict['Road'] = road
        data_dict['land size'] = land 
        data_dict['parking size'] = parking.text


        data_dict['bedroom'] = bedroom.text
        data_dict['bathroom'] = bathroom.text    
        data_dict['built year'] = builty.text
        data_dict['direction'] = direction.text

        data_dict['url']=url
        # Print the dictionary
        data_list.append(data_dict)
    except:
        continue

end_time = time.time()

In [1]:
print(data_list)

NameError: name 'data_list' is not defined

In [82]:
import pandas as pd

df = pd.DataFrame(data_list)
df.to_csv('houses.csv',index=False)
df_input = pd.read_csv('houses.csv')
df_input.tail()

,title,price,location,Road,land size,parking size,bedroom,bathroom,built year,direction,url
685,House for sale at Kapan 10 Budhanilkantha | 98...,"1,25,00,000","Kapan 10 Budhanilkantha\nKathmandu, State 4",8 Ft,2.5 A,NaN,4,3,NaN,NaN,https://www.gharghaderi.com/house/385-House-fo...
686,House for sale in Sukedhara | 9840872228,"1,72,00,000","Sukedhara 1 Budhanilkantha\nKathmandu, State 3",13 Ft,0-3-0-0,NaN,NaN,NaN,NaN,south west,https://www.gharghaderi.com/house/371-House-fo...
687,Semi furnished house for sale at Samakhusi Kat...,"2,35,00,000","Samakhusi 14 KMC\nKathmandu, State 4",12 Ft,4 A,car 1,5+,4,2075,NaN,https://www.gharghaderi.com/house/359-Semi-fur...
688,Ghar bikrima | 9843426142,"1,95,00,000","Kadaghari 1 Kageshwori-Manohara\nKathmandu , S...",12 Ft,3.2.2.,Car 1,NaN,NaN,2072,North,https://www.gharghaderi.com/house/357-Ghar-bik...
689,1.5 story new house at Pokhara 10 Nayagaun | 9...,"1,85,00,000","Nayagaun 10 PMC\nKaski, Gandaki",12 Feet,20/40,car 1,3,2,NaN,east,https://www.gharghaderi.com/house/340-1.5-stor...